package day51_ExceptionRecap;

public class C07_Throws2 {

    public static void main(String[] args) throws ArithmeticException {

        System.out.println("test");

        System.out.println(5/0);//unchecked---only and only with try and catch

        System.out.println("test completed");


    }
}
